# Site settings
ref: CSCC09
title: Programming on the Web
edition: Fall 2026
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.me/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/utoronto.ca/fall2026/cscc09
feedback: https://forms.gle/G7nMnduQEGchN77F8

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Wed 4 PM - 5 PM
  location: IA 4124
  contact: Piazza only (no email)
  role: Prof.

assistants:
    - name: Arshiya Mahmoodinezhad
      contact: Piazza only
      hours: Tue 10 AM - 11 AM
      location: IA 3180 (CS Help Center)
    - name: Kevin Zhang
      contact: Piazza only
      hours: Thu 4 - 5 PM
      location: IA 3180 (CS Help Center)

timings:
    - section: LEC01
      time: Wed 11 AM - 1PM
      location: IA 2050
      instructor: Thierry Sans
    - section: LEC02
      time: Wed 2 - 4 PM
      location: IA 3120
      instructor: Thierry Sans

first: 20260907